### ISSUE TITLE
Question about the `local attention residual term`

### ISSUE THREAD

**Issue by Journey7331** [LeapLabTHU/InLine#3]
Thanks for your insightful work!

I have a question that cannot be answered from your paper:

The `local attention residual term` seems quite similar with dw-conv-3x3 or lepe, but in your code implementation, you use a simple mlp to gain conv weights.

How was this idea come? 
Is any difference between a direct dwconv?

**Comment by Journey7331** [comment]
Sorry for bothering

Here you use `(self.scale / n) ** 0.5)` for numerical stability, but the result seems not be recovered?
Unmatch with your paper eq(5)?


https://github.com/LeapLabTHU/InLine/blob/6103e64262b196f776b5b205187851aff3101143/models/inline_swin.py#L267-L268

**Comment by tian-qing001** [comment]
Hi @Journey7331, thanks for your attention to our work.

1. The implementation of local attention residual is consistent with eq. 6 in our paper. This term is similar to local attention since it uses input-dependent weights to aggregate local values. In our code, `F.conv` is utilized to implement this term efficiently.
2. The `self.scale / n = head_dim ** -0.5 / n` is a scale factor used in InLine attention, similar to the role of `head_dim ** -0.5` in Softmax attention. As this factor can be equivalently achieved by scaling `\phi(Q) = \phi(Q) * self.scale / n` _**before**_ the InLine attention calculation (eq. 5 of the paper), we omit it in eq. 5 for simplicity.

**Comment by Journey7331** [comment]
Thx for your quick reply!
1. So, Any ablation experiments about exact drop between `local attention res` and `dwconv`?
2. So this final scale is a `empirical value`, similar to (d**-0.5), but not the same value (overdivided by n)?

**Comment by tian-qing001** [comment]
1. The local attention residual commonly delivers around 0.1-0.2 accuracy gain compared to dwc.
2. Yes.

**Comment by Journey7331** [comment]
Helps a lot!!
